[package]
name = "zlosynth_github_io"
version = "0.1.0"
authors = ["Petr Horáček <hrck@protonmail.com>"]
edition = "2018"
publish = false
build = "build.rs"

[dependencies]
heapnotize = "1.0"
skeptic = "0.13"

[build-dependencies]
skeptic = "0.13"
